INSERT INTO `im_user` (`id`, `user_name`, `nick_name`, `head_image`, `head_image_thumb`, `password`, `sex`, `signature`, `qq_open_id`, `qq_access_token`, `login_type`, `is_disable`, `ip_address`, `ip_source`, `province`, `city`, `last_login_time`, `create_time`) VALUES (1, 'admin', '管理员', '', '', '$2a$10$hU77e62KP4XKxDa4/rXJ2.Z7qLGpwFpFWJvFrl1N9NnEInJHsD4kW', 0, '', NULL, NULL, 0, 0, '127.0.0.1', '', '', '', '2023-08-12 15:49:56', '2023-02-19 15:21:09');


INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (1, 0, '开启', '1', 'sys_media_switch', NULL, 'success', 'N', '0', 'admin', '2023-05-02 16:41:52', 'admin', '2023-05-02 17:10:32', NULL);
INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (2, 0, '开启', '1', 'home_media_switch', NULL, 'success', 'N', '0', 'admin', '2023-05-02 16:41:52', 'admin', '2023-05-02 17:10:32', NULL);
INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (3, 0, '公共群组', '1', 'common_group', NULL, 'success', 'N', '0', 'admin', '2024-04-27 14:17:51', '', NULL, NULL);
INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (4, 0, '是否开启图片检测', 'NO', 'open_image_detect', NULL, 'success', 'N', '0', 'admin', '2024-10-16 10:08:35', '', NULL, NULL);
INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (5, 0, '是否添加新注册用户', 'YES', 'new_register_user', NULL, 'success', 'N', '0', 'admin', '2024-10-10 15:53:58', '', NULL, NULL);
INSERT INTO `im_dict_data` (`dict_code`, `dict_sort`, `dict_label`, `dict_value`, `dict_type`, `css_class`, `list_class`, `is_default`, `status`, `create_by`, `create_time`, `update_by`, `update_time`, `remark`) VALUES (6, 0, '禁止网站聊天功能', 'YES', 'website_message_ban', NULL, 'success', 'N', '0', 'admin', '2024-10-21 12:36:48', '', NULL, NULL);
